"""empty message

Revision ID: 3b9387ed7ef1
Revises: ee2756b74bf0
Create Date: 2018-12-12 15:25:55.251359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b9387ed7ef1'
down_revision = 'ee2756b74bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_news', 'reason')
    op.drop_column('info_news', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_news', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('info_news', sa.Column('reason', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
