"""empty message

Revision ID: 7436505dfce1
Revises: e5ccbde88370
Create Date: 2018-12-12 15:12:55.518394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7436505dfce1'
down_revision = 'e5ccbde88370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_user', sa.Column('addrs', sa.String(length=128), nullable=False))
    op.add_column('info_user', sa.Column('job', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_user', 'job')
    op.drop_column('info_user', 'addrs')
    # ### end Alembic commands ###
