"""empty message

Revision ID: 78aff81c79fe
Revises: 7436505dfce1
Create Date: 2018-12-12 15:14:58.329524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78aff81c79fe'
down_revision = '7436505dfce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='info_user')
    op.drop_column('info_user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_user', sa.Column('email', mysql.VARCHAR(length=11), nullable=False))
    op.create_index('email', 'info_user', ['email'], unique=True)
    # ### end Alembic commands ###
